/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IpmatIndexRouteImport } from './routes/ipmat.index'
import { Route as FaqIndexRouteImport } from './routes/faq.index'
import { Route as FacultyIndexRouteImport } from './routes/faculty.index'
import { Route as CuetIndexRouteImport } from './routes/cuet.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CentresIndexRouteImport } from './routes/centres.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as IpmatWorthItRouteImport } from './routes/ipmat.worth-it'
import { Route as IpmatWellbeingRouteImport } from './routes/ipmat.wellbeing'
import { Route as IpmatWatRouteImport } from './routes/ipmat.wat'
import { Route as IpmatSelfStudyVsCoachingRouteImport } from './routes/ipmat.self-study-vs-coaching'
import { Route as IpmatSectionalLockRouteImport } from './routes/ipmat.sectional-lock'
import { Route as IpmatSafeScoreRouteImport } from './routes/ipmat.safe-score'
import { Route as IpmatRoiRouteImport } from './routes/ipmat.roi'
import { Route as IpmatProfileBuildingRouteImport } from './routes/ipmat.profile-building'
import { Route as IpmatParentsGuideRouteImport } from './routes/ipmat.parents-guide'
import { Route as IpmatMarkingSchemeRouteImport } from './routes/ipmat.marking-scheme'
import { Route as IpmatImportantDatesRouteImport } from './routes/ipmat.important-dates'
import { Route as IpmatFaqRouteImport } from './routes/ipmat.faq'
import { Route as IpmatExamRouteImport } from './routes/ipmat.exam'
import { Route as IpmatEligibilityRouteImport } from './routes/ipmat.eligibility'
import { Route as IpmatCutoffRouteImport } from './routes/ipmat.cutoff'
import { Route as IpmatCoachingInNoidaRouteImport } from './routes/ipmat.coaching-in-noida'
import { Route as IpmatCoachingInHauzKhasRouteImport } from './routes/ipmat.coaching-in-hauz-khas'
import { Route as IpmatCoachingInGurugramRouteImport } from './routes/ipmat.coaching-in-gurugram'
import { Route as IpmatCoachingInGtbNagarRouteImport } from './routes/ipmat.coaching-in-gtb-nagar'
import { Route as IpmatCoachingInDelhiNcrRouteImport } from './routes/ipmat.coaching-in-delhi-ncr'
import { Route as IpmatCampusLifeRouteImport } from './routes/ipmat.campus-life'
import { Route as IpmatBooksMocksRouteImport } from './routes/ipmat.books-mocks'
import { Route as IpmatApplicationProcessRouteImport } from './routes/ipmat.application-process'
import { Route as FaqIpmatRouteImport } from './routes/faq.ipmat'
import { Route as FaqCuetRouteImport } from './routes/faq.cuet'
import { Route as FacultySlugRouteImport } from './routes/faculty.$slug'
import { Route as CuetWithoutCoachingRouteImport } from './routes/cuet.without-coaching'
import { Route as CuetToppersRouteImport } from './routes/cuet.toppers'
import { Route as CuetSubjectRulesRouteImport } from './routes/cuet.subject-rules'
import { Route as CuetPolicyRouteImport } from './routes/cuet.policy'
import { Route as CuetParentsGuideRouteImport } from './routes/cuet.parents-guide'
import { Route as CuetMarkingRouteImport } from './routes/cuet.marking'
import { Route as CuetLanguagesRouteImport } from './routes/cuet.languages'
import { Route as CuetIsCuetHardRouteImport } from './routes/cuet.is-cuet-hard'
import { Route as CuetHistoryRouteImport } from './routes/cuet.history'
import { Route as CuetFaqRouteImport } from './routes/cuet.faq'
import { Route as CuetExamPatternRouteImport } from './routes/cuet.exam-pattern'
import { Route as CuetExamDayRouteImport } from './routes/cuet.exam-day'
import { Route as CuetEligibilityRouteImport } from './routes/cuet.eligibility'
import { Route as CuetCoachingInNoidaRouteImport } from './routes/cuet.coaching-in-noida'
import { Route as CuetCoachingInHauzKhasRouteImport } from './routes/cuet.coaching-in-hauz-khas'
import { Route as CuetCoachingInGurugramRouteImport } from './routes/cuet.coaching-in-gurugram'
import { Route as CuetCoachingInGtbNagarRouteImport } from './routes/cuet.coaching-in-gtb-nagar'
import { Route as CuetCoachingInDelhiNcrRouteImport } from './routes/cuet.coaching-in-delhi-ncr'
import { Route as CuetCitySlipRouteImport } from './routes/cuet.city-slip'
import { Route as CuetChangesRouteImport } from './routes/cuet.changes'
import { Route as CuetAdmitCardRouteImport } from './routes/cuet.admit-card'
import { Route as CoursesIpmatRouteImport } from './routes/courses.ipmat'
import { Route as CoursesCuetRouteImport } from './routes/courses.cuet'
import { Route as CentresSlugRouteImport } from './routes/centres.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as IpmatSyllabusIndexRouteImport } from './routes/ipmat.syllabus.index'
import { Route as IpmatCompareIndexRouteImport } from './routes/ipmat.compare.index'
import { Route as IpmatCollegesIndexRouteImport } from './routes/ipmat.colleges.index'
import { Route as CuetSyllabusIndexRouteImport } from './routes/cuet.syllabus.index'
import { Route as CuetResultsIndexRouteImport } from './routes/cuet.results.index'
import { Route as CuetExamCentersIndexRouteImport } from './routes/cuet.exam-centers.index'
import { Route as CuetCutoffIndexRouteImport } from './routes/cuet.cutoff.index'
import { Route as CuetCompareIndexRouteImport } from './routes/cuet.compare.index'
import { Route as CuetCollegesIndexRouteImport } from './routes/cuet.colleges.index'
import { Route as CuetAdmissionIndexRouteImport } from './routes/cuet.admission.index'
import { Route as IpmatSyllabusSectionRouteImport } from './routes/ipmat.syllabus.$section'
import { Route as IpmatSectionStrategySectionRouteImport } from './routes/ipmat.section-strategy.$section'
import { Route as IpmatProgrammeStructureRouteImport } from './routes/ipmat.programme.structure'
import { Route as IpmatPreparationDurationRouteImport } from './routes/ipmat.preparation.$duration'
import { Route as IpmatPlacementsInstituteRouteImport } from './routes/ipmat.placements.$institute'
import { Route as IpmatInterviewInstituteRouteImport } from './routes/ipmat.interview.$institute'
import { Route as IpmatCompositeScoreInstituteRouteImport } from './routes/ipmat.composite-score.$institute'
import { Route as IpmatCompareIpmVsBbaRouteImport } from './routes/ipmat.compare.ipm-vs-bba'
import { Route as IpmatCompareIndoreVsRohtakRouteImport } from './routes/ipmat.compare.indore-vs-rohtak'
import { Route as IpmatCollegesInstituteRouteImport } from './routes/ipmat.colleges.$institute'
import { Route as IpmatCityCityRouteImport } from './routes/ipmat.city.$city'
import { Route as IpmatAdmissionInstituteRouteImport } from './routes/ipmat.admission.$institute'
import { Route as CuetStudyPlanDurationRouteImport } from './routes/cuet.study-plan.$duration'
import { Route as CuetResultsScorecardRouteImport } from './routes/cuet.results.scorecard'
import { Route as CuetResultsScoreCalculatorRouteImport } from './routes/cuet.results.score-calculator'
import { Route as CuetResultsNormalizationRouteImport } from './routes/cuet.results.normalization'
import { Route as CuetResultsMarksVsPercentileRouteImport } from './routes/cuet.results.marks-vs-percentile'
import { Route as CuetNewsSlugRouteImport } from './routes/cuet.news.$slug'
import { Route as CuetExamCentersCityRouteImport } from './routes/cuet.exam-centers.$city'
import { Route as CuetCutoffHowCutoffsWorkRouteImport } from './routes/cuet.cutoff.how-cutoffs-work'
import { Route as CuetCutoffDatasetRouteImport } from './routes/cuet.cutoff.dataset'
import { Route as CuetCompareQuizRouteImport } from './routes/cuet.compare.quiz'
import { Route as CuetCompareCuetVsIpmatRouteImport } from './routes/cuet.compare.cuet-vs-ipmat'
import { Route as CuetCompareMatchupRouteImport } from './routes/cuet.compare.$matchup'
import { Route as CuetAdmissionSpotRoundRouteImport } from './routes/cuet.admission.spot-round'
import { Route as CuetAdmissionFreezeVsUpgradeRouteImport } from './routes/cuet.admission.freeze-vs-upgrade'
import { Route as CuetResultsCollegePredictorIndexRouteImport } from './routes/cuet.results.college-predictor.index'
import { Route as IpmatProgrammeInstituteFeesRouteImport } from './routes/ipmat.programme.$institute.fees'
import { Route as CuetCutoffCollegesForBandRouteImport } from './routes/cuet.cutoff.colleges-for.$band'
import { Route as CuetCollegesBestForCourseRouteImport } from './routes/cuet.colleges.best-for.$course'
import { Route as CuetCollegesUniversityCollegeRouteImport } from './routes/cuet.colleges.$university.$college'
import { Route as CuetResultsCollegePredictorUniversityCourseRouteImport } from './routes/cuet.results.college-predictor.$university.$course'
import { Route as CuetCutoffUniversityCollegeCourseRouteImport } from './routes/cuet.cutoff.$university.$college.$course'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatIndexRoute = IpmatIndexRouteImport.update({
  id: '/ipmat/',
  path: '/ipmat/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqIndexRoute = FaqIndexRouteImport.update({
  id: '/faq/',
  path: '/faq/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyIndexRoute = FacultyIndexRouteImport.update({
  id: '/faculty/',
  path: '/faculty/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetIndexRoute = CuetIndexRouteImport.update({
  id: '/cuet/',
  path: '/cuet/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentresIndexRoute = CentresIndexRouteImport.update({
  id: '/centres/',
  path: '/centres/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatWorthItRoute = IpmatWorthItRouteImport.update({
  id: '/ipmat/worth-it',
  path: '/ipmat/worth-it',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatWellbeingRoute = IpmatWellbeingRouteImport.update({
  id: '/ipmat/wellbeing',
  path: '/ipmat/wellbeing',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatWatRoute = IpmatWatRouteImport.update({
  id: '/ipmat/wat',
  path: '/ipmat/wat',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatSelfStudyVsCoachingRoute =
  IpmatSelfStudyVsCoachingRouteImport.update({
    id: '/ipmat/self-study-vs-coaching',
    path: '/ipmat/self-study-vs-coaching',
    getParentRoute: () => rootRouteImport,
  } as any)
const IpmatSectionalLockRoute = IpmatSectionalLockRouteImport.update({
  id: '/ipmat/sectional-lock',
  path: '/ipmat/sectional-lock',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatSafeScoreRoute = IpmatSafeScoreRouteImport.update({
  id: '/ipmat/safe-score',
  path: '/ipmat/safe-score',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatRoiRoute = IpmatRoiRouteImport.update({
  id: '/ipmat/roi',
  path: '/ipmat/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatProfileBuildingRoute = IpmatProfileBuildingRouteImport.update({
  id: '/ipmat/profile-building',
  path: '/ipmat/profile-building',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatParentsGuideRoute = IpmatParentsGuideRouteImport.update({
  id: '/ipmat/parents-guide',
  path: '/ipmat/parents-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatMarkingSchemeRoute = IpmatMarkingSchemeRouteImport.update({
  id: '/ipmat/marking-scheme',
  path: '/ipmat/marking-scheme',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatImportantDatesRoute = IpmatImportantDatesRouteImport.update({
  id: '/ipmat/important-dates',
  path: '/ipmat/important-dates',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatFaqRoute = IpmatFaqRouteImport.update({
  id: '/ipmat/faq',
  path: '/ipmat/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatExamRoute = IpmatExamRouteImport.update({
  id: '/ipmat/exam',
  path: '/ipmat/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatEligibilityRoute = IpmatEligibilityRouteImport.update({
  id: '/ipmat/eligibility',
  path: '/ipmat/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatCutoffRoute = IpmatCutoffRouteImport.update({
  id: '/ipmat/cutoff',
  path: '/ipmat/cutoff',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatCoachingInNoidaRoute = IpmatCoachingInNoidaRouteImport.update({
  id: '/ipmat/coaching-in-noida',
  path: '/ipmat/coaching-in-noida',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatCoachingInHauzKhasRoute = IpmatCoachingInHauzKhasRouteImport.update({
  id: '/ipmat/coaching-in-hauz-khas',
  path: '/ipmat/coaching-in-hauz-khas',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatCoachingInGurugramRoute = IpmatCoachingInGurugramRouteImport.update({
  id: '/ipmat/coaching-in-gurugram',
  path: '/ipmat/coaching-in-gurugram',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatCoachingInGtbNagarRoute = IpmatCoachingInGtbNagarRouteImport.update({
  id: '/ipmat/coaching-in-gtb-nagar',
  path: '/ipmat/coaching-in-gtb-nagar',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatCoachingInDelhiNcrRoute = IpmatCoachingInDelhiNcrRouteImport.update({
  id: '/ipmat/coaching-in-delhi-ncr',
  path: '/ipmat/coaching-in-delhi-ncr',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatCampusLifeRoute = IpmatCampusLifeRouteImport.update({
  id: '/ipmat/campus-life',
  path: '/ipmat/campus-life',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatBooksMocksRoute = IpmatBooksMocksRouteImport.update({
  id: '/ipmat/books-mocks',
  path: '/ipmat/books-mocks',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatApplicationProcessRoute = IpmatApplicationProcessRouteImport.update({
  id: '/ipmat/application-process',
  path: '/ipmat/application-process',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqIpmatRoute = FaqIpmatRouteImport.update({
  id: '/faq/ipmat',
  path: '/faq/ipmat',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqCuetRoute = FaqCuetRouteImport.update({
  id: '/faq/cuet',
  path: '/faq/cuet',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultySlugRoute = FacultySlugRouteImport.update({
  id: '/faculty/$slug',
  path: '/faculty/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetWithoutCoachingRoute = CuetWithoutCoachingRouteImport.update({
  id: '/cuet/without-coaching',
  path: '/cuet/without-coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetToppersRoute = CuetToppersRouteImport.update({
  id: '/cuet/toppers',
  path: '/cuet/toppers',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetSubjectRulesRoute = CuetSubjectRulesRouteImport.update({
  id: '/cuet/subject-rules',
  path: '/cuet/subject-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetPolicyRoute = CuetPolicyRouteImport.update({
  id: '/cuet/policy',
  path: '/cuet/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetParentsGuideRoute = CuetParentsGuideRouteImport.update({
  id: '/cuet/parents-guide',
  path: '/cuet/parents-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetMarkingRoute = CuetMarkingRouteImport.update({
  id: '/cuet/marking',
  path: '/cuet/marking',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetLanguagesRoute = CuetLanguagesRouteImport.update({
  id: '/cuet/languages',
  path: '/cuet/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetIsCuetHardRoute = CuetIsCuetHardRouteImport.update({
  id: '/cuet/is-cuet-hard',
  path: '/cuet/is-cuet-hard',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetHistoryRoute = CuetHistoryRouteImport.update({
  id: '/cuet/history',
  path: '/cuet/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetFaqRoute = CuetFaqRouteImport.update({
  id: '/cuet/faq',
  path: '/cuet/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetExamPatternRoute = CuetExamPatternRouteImport.update({
  id: '/cuet/exam-pattern',
  path: '/cuet/exam-pattern',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetExamDayRoute = CuetExamDayRouteImport.update({
  id: '/cuet/exam-day',
  path: '/cuet/exam-day',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetEligibilityRoute = CuetEligibilityRouteImport.update({
  id: '/cuet/eligibility',
  path: '/cuet/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetCoachingInNoidaRoute = CuetCoachingInNoidaRouteImport.update({
  id: '/cuet/coaching-in-noida',
  path: '/cuet/coaching-in-noida',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetCoachingInHauzKhasRoute = CuetCoachingInHauzKhasRouteImport.update({
  id: '/cuet/coaching-in-hauz-khas',
  path: '/cuet/coaching-in-hauz-khas',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetCoachingInGurugramRoute = CuetCoachingInGurugramRouteImport.update({
  id: '/cuet/coaching-in-gurugram',
  path: '/cuet/coaching-in-gurugram',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetCoachingInGtbNagarRoute = CuetCoachingInGtbNagarRouteImport.update({
  id: '/cuet/coaching-in-gtb-nagar',
  path: '/cuet/coaching-in-gtb-nagar',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetCoachingInDelhiNcrRoute = CuetCoachingInDelhiNcrRouteImport.update({
  id: '/cuet/coaching-in-delhi-ncr',
  path: '/cuet/coaching-in-delhi-ncr',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetCitySlipRoute = CuetCitySlipRouteImport.update({
  id: '/cuet/city-slip',
  path: '/cuet/city-slip',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetChangesRoute = CuetChangesRouteImport.update({
  id: '/cuet/changes',
  path: '/cuet/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetAdmitCardRoute = CuetAdmitCardRouteImport.update({
  id: '/cuet/admit-card',
  path: '/cuet/admit-card',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIpmatRoute = CoursesIpmatRouteImport.update({
  id: '/courses/ipmat',
  path: '/courses/ipmat',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCuetRoute = CoursesCuetRouteImport.update({
  id: '/courses/cuet',
  path: '/courses/cuet',
  getParentRoute: () => rootRouteImport,
} as any)
const CentresSlugRoute = CentresSlugRouteImport.update({
  id: '/centres/$slug',
  path: '/centres/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatSyllabusIndexRoute = IpmatSyllabusIndexRouteImport.update({
  id: '/ipmat/syllabus/',
  path: '/ipmat/syllabus/',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatCompareIndexRoute = IpmatCompareIndexRouteImport.update({
  id: '/ipmat/compare/',
  path: '/ipmat/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatCollegesIndexRoute = IpmatCollegesIndexRouteImport.update({
  id: '/ipmat/colleges/',
  path: '/ipmat/colleges/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetSyllabusIndexRoute = CuetSyllabusIndexRouteImport.update({
  id: '/cuet/syllabus/',
  path: '/cuet/syllabus/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetResultsIndexRoute = CuetResultsIndexRouteImport.update({
  id: '/cuet/results/',
  path: '/cuet/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetExamCentersIndexRoute = CuetExamCentersIndexRouteImport.update({
  id: '/cuet/exam-centers/',
  path: '/cuet/exam-centers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetCutoffIndexRoute = CuetCutoffIndexRouteImport.update({
  id: '/cuet/cutoff/',
  path: '/cuet/cutoff/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetCompareIndexRoute = CuetCompareIndexRouteImport.update({
  id: '/cuet/compare/',
  path: '/cuet/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetCollegesIndexRoute = CuetCollegesIndexRouteImport.update({
  id: '/cuet/colleges/',
  path: '/cuet/colleges/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetAdmissionIndexRoute = CuetAdmissionIndexRouteImport.update({
  id: '/cuet/admission/',
  path: '/cuet/admission/',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatSyllabusSectionRoute = IpmatSyllabusSectionRouteImport.update({
  id: '/ipmat/syllabus/$section',
  path: '/ipmat/syllabus/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatSectionStrategySectionRoute =
  IpmatSectionStrategySectionRouteImport.update({
    id: '/ipmat/section-strategy/$section',
    path: '/ipmat/section-strategy/$section',
    getParentRoute: () => rootRouteImport,
  } as any)
const IpmatProgrammeStructureRoute = IpmatProgrammeStructureRouteImport.update({
  id: '/ipmat/programme/structure',
  path: '/ipmat/programme/structure',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatPreparationDurationRoute =
  IpmatPreparationDurationRouteImport.update({
    id: '/ipmat/preparation/$duration',
    path: '/ipmat/preparation/$duration',
    getParentRoute: () => rootRouteImport,
  } as any)
const IpmatPlacementsInstituteRoute =
  IpmatPlacementsInstituteRouteImport.update({
    id: '/ipmat/placements/$institute',
    path: '/ipmat/placements/$institute',
    getParentRoute: () => rootRouteImport,
  } as any)
const IpmatInterviewInstituteRoute = IpmatInterviewInstituteRouteImport.update({
  id: '/ipmat/interview/$institute',
  path: '/ipmat/interview/$institute',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatCompositeScoreInstituteRoute =
  IpmatCompositeScoreInstituteRouteImport.update({
    id: '/ipmat/composite-score/$institute',
    path: '/ipmat/composite-score/$institute',
    getParentRoute: () => rootRouteImport,
  } as any)
const IpmatCompareIpmVsBbaRoute = IpmatCompareIpmVsBbaRouteImport.update({
  id: '/ipmat/compare/ipm-vs-bba',
  path: '/ipmat/compare/ipm-vs-bba',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatCompareIndoreVsRohtakRoute =
  IpmatCompareIndoreVsRohtakRouteImport.update({
    id: '/ipmat/compare/indore-vs-rohtak',
    path: '/ipmat/compare/indore-vs-rohtak',
    getParentRoute: () => rootRouteImport,
  } as any)
const IpmatCollegesInstituteRoute = IpmatCollegesInstituteRouteImport.update({
  id: '/ipmat/colleges/$institute',
  path: '/ipmat/colleges/$institute',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatCityCityRoute = IpmatCityCityRouteImport.update({
  id: '/ipmat/city/$city',
  path: '/ipmat/city/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const IpmatAdmissionInstituteRoute = IpmatAdmissionInstituteRouteImport.update({
  id: '/ipmat/admission/$institute',
  path: '/ipmat/admission/$institute',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetStudyPlanDurationRoute = CuetStudyPlanDurationRouteImport.update({
  id: '/cuet/study-plan/$duration',
  path: '/cuet/study-plan/$duration',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetResultsScorecardRoute = CuetResultsScorecardRouteImport.update({
  id: '/cuet/results/scorecard',
  path: '/cuet/results/scorecard',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetResultsScoreCalculatorRoute =
  CuetResultsScoreCalculatorRouteImport.update({
    id: '/cuet/results/score-calculator',
    path: '/cuet/results/score-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const CuetResultsNormalizationRoute =
  CuetResultsNormalizationRouteImport.update({
    id: '/cuet/results/normalization',
    path: '/cuet/results/normalization',
    getParentRoute: () => rootRouteImport,
  } as any)
const CuetResultsMarksVsPercentileRoute =
  CuetResultsMarksVsPercentileRouteImport.update({
    id: '/cuet/results/marks-vs-percentile',
    path: '/cuet/results/marks-vs-percentile',
    getParentRoute: () => rootRouteImport,
  } as any)
const CuetNewsSlugRoute = CuetNewsSlugRouteImport.update({
  id: '/cuet/news/$slug',
  path: '/cuet/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetExamCentersCityRoute = CuetExamCentersCityRouteImport.update({
  id: '/cuet/exam-centers/$city',
  path: '/cuet/exam-centers/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetCutoffHowCutoffsWorkRoute =
  CuetCutoffHowCutoffsWorkRouteImport.update({
    id: '/cuet/cutoff/how-cutoffs-work',
    path: '/cuet/cutoff/how-cutoffs-work',
    getParentRoute: () => rootRouteImport,
  } as any)
const CuetCutoffDatasetRoute = CuetCutoffDatasetRouteImport.update({
  id: '/cuet/cutoff/dataset',
  path: '/cuet/cutoff/dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetCompareQuizRoute = CuetCompareQuizRouteImport.update({
  id: '/cuet/compare/quiz',
  path: '/cuet/compare/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetCompareCuetVsIpmatRoute = CuetCompareCuetVsIpmatRouteImport.update({
  id: '/cuet/compare/cuet-vs-ipmat',
  path: '/cuet/compare/cuet-vs-ipmat',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetCompareMatchupRoute = CuetCompareMatchupRouteImport.update({
  id: '/cuet/compare/$matchup',
  path: '/cuet/compare/$matchup',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetAdmissionSpotRoundRoute = CuetAdmissionSpotRoundRouteImport.update({
  id: '/cuet/admission/spot-round',
  path: '/cuet/admission/spot-round',
  getParentRoute: () => rootRouteImport,
} as any)
const CuetAdmissionFreezeVsUpgradeRoute =
  CuetAdmissionFreezeVsUpgradeRouteImport.update({
    id: '/cuet/admission/freeze-vs-upgrade',
    path: '/cuet/admission/freeze-vs-upgrade',
    getParentRoute: () => rootRouteImport,
  } as any)
const CuetResultsCollegePredictorIndexRoute =
  CuetResultsCollegePredictorIndexRouteImport.update({
    id: '/cuet/results/college-predictor/',
    path: '/cuet/results/college-predictor/',
    getParentRoute: () => rootRouteImport,
  } as any)
const IpmatProgrammeInstituteFeesRoute =
  IpmatProgrammeInstituteFeesRouteImport.update({
    id: '/ipmat/programme/$institute/fees',
    path: '/ipmat/programme/$institute/fees',
    getParentRoute: () => rootRouteImport,
  } as any)
const CuetCutoffCollegesForBandRoute =
  CuetCutoffCollegesForBandRouteImport.update({
    id: '/cuet/cutoff/colleges-for/$band',
    path: '/cuet/cutoff/colleges-for/$band',
    getParentRoute: () => rootRouteImport,
  } as any)
const CuetCollegesBestForCourseRoute =
  CuetCollegesBestForCourseRouteImport.update({
    id: '/cuet/colleges/best-for/$course',
    path: '/cuet/colleges/best-for/$course',
    getParentRoute: () => rootRouteImport,
  } as any)
const CuetCollegesUniversityCollegeRoute =
  CuetCollegesUniversityCollegeRouteImport.update({
    id: '/cuet/colleges/$university/$college',
    path: '/cuet/colleges/$university/$college',
    getParentRoute: () => rootRouteImport,
  } as any)
const CuetResultsCollegePredictorUniversityCourseRoute =
  CuetResultsCollegePredictorUniversityCourseRouteImport.update({
    id: '/cuet/results/college-predictor/$university/$course',
    path: '/cuet/results/college-predictor/$university/$course',
    getParentRoute: () => rootRouteImport,
  } as any)
const CuetCutoffUniversityCollegeCourseRoute =
  CuetCutoffUniversityCollegeCourseRouteImport.update({
    id: '/cuet/cutoff/$university/$college/$course',
    path: '/cuet/cutoff/$university/$college/$course',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/centres/$slug': typeof CentresSlugRoute
  '/courses/cuet': typeof CoursesCuetRoute
  '/courses/ipmat': typeof CoursesIpmatRoute
  '/cuet/admit-card': typeof CuetAdmitCardRoute
  '/cuet/changes': typeof CuetChangesRoute
  '/cuet/city-slip': typeof CuetCitySlipRoute
  '/cuet/coaching-in-delhi-ncr': typeof CuetCoachingInDelhiNcrRoute
  '/cuet/coaching-in-gtb-nagar': typeof CuetCoachingInGtbNagarRoute
  '/cuet/coaching-in-gurugram': typeof CuetCoachingInGurugramRoute
  '/cuet/coaching-in-hauz-khas': typeof CuetCoachingInHauzKhasRoute
  '/cuet/coaching-in-noida': typeof CuetCoachingInNoidaRoute
  '/cuet/eligibility': typeof CuetEligibilityRoute
  '/cuet/exam-day': typeof CuetExamDayRoute
  '/cuet/exam-pattern': typeof CuetExamPatternRoute
  '/cuet/faq': typeof CuetFaqRoute
  '/cuet/history': typeof CuetHistoryRoute
  '/cuet/is-cuet-hard': typeof CuetIsCuetHardRoute
  '/cuet/languages': typeof CuetLanguagesRoute
  '/cuet/marking': typeof CuetMarkingRoute
  '/cuet/parents-guide': typeof CuetParentsGuideRoute
  '/cuet/policy': typeof CuetPolicyRoute
  '/cuet/subject-rules': typeof CuetSubjectRulesRoute
  '/cuet/toppers': typeof CuetToppersRoute
  '/cuet/without-coaching': typeof CuetWithoutCoachingRoute
  '/faculty/$slug': typeof FacultySlugRoute
  '/faq/cuet': typeof FaqCuetRoute
  '/faq/ipmat': typeof FaqIpmatRoute
  '/ipmat/application-process': typeof IpmatApplicationProcessRoute
  '/ipmat/books-mocks': typeof IpmatBooksMocksRoute
  '/ipmat/campus-life': typeof IpmatCampusLifeRoute
  '/ipmat/coaching-in-delhi-ncr': typeof IpmatCoachingInDelhiNcrRoute
  '/ipmat/coaching-in-gtb-nagar': typeof IpmatCoachingInGtbNagarRoute
  '/ipmat/coaching-in-gurugram': typeof IpmatCoachingInGurugramRoute
  '/ipmat/coaching-in-hauz-khas': typeof IpmatCoachingInHauzKhasRoute
  '/ipmat/coaching-in-noida': typeof IpmatCoachingInNoidaRoute
  '/ipmat/cutoff': typeof IpmatCutoffRoute
  '/ipmat/eligibility': typeof IpmatEligibilityRoute
  '/ipmat/exam': typeof IpmatExamRoute
  '/ipmat/faq': typeof IpmatFaqRoute
  '/ipmat/important-dates': typeof IpmatImportantDatesRoute
  '/ipmat/marking-scheme': typeof IpmatMarkingSchemeRoute
  '/ipmat/parents-guide': typeof IpmatParentsGuideRoute
  '/ipmat/profile-building': typeof IpmatProfileBuildingRoute
  '/ipmat/roi': typeof IpmatRoiRoute
  '/ipmat/safe-score': typeof IpmatSafeScoreRoute
  '/ipmat/sectional-lock': typeof IpmatSectionalLockRoute
  '/ipmat/self-study-vs-coaching': typeof IpmatSelfStudyVsCoachingRoute
  '/ipmat/wat': typeof IpmatWatRoute
  '/ipmat/wellbeing': typeof IpmatWellbeingRoute
  '/ipmat/worth-it': typeof IpmatWorthItRoute
  '/blog/': typeof BlogIndexRoute
  '/centres/': typeof CentresIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/cuet/': typeof CuetIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/faq/': typeof FaqIndexRoute
  '/ipmat/': typeof IpmatIndexRoute
  '/cuet/admission/freeze-vs-upgrade': typeof CuetAdmissionFreezeVsUpgradeRoute
  '/cuet/admission/spot-round': typeof CuetAdmissionSpotRoundRoute
  '/cuet/compare/$matchup': typeof CuetCompareMatchupRoute
  '/cuet/compare/cuet-vs-ipmat': typeof CuetCompareCuetVsIpmatRoute
  '/cuet/compare/quiz': typeof CuetCompareQuizRoute
  '/cuet/cutoff/dataset': typeof CuetCutoffDatasetRoute
  '/cuet/cutoff/how-cutoffs-work': typeof CuetCutoffHowCutoffsWorkRoute
  '/cuet/exam-centers/$city': typeof CuetExamCentersCityRoute
  '/cuet/news/$slug': typeof CuetNewsSlugRoute
  '/cuet/results/marks-vs-percentile': typeof CuetResultsMarksVsPercentileRoute
  '/cuet/results/normalization': typeof CuetResultsNormalizationRoute
  '/cuet/results/score-calculator': typeof CuetResultsScoreCalculatorRoute
  '/cuet/results/scorecard': typeof CuetResultsScorecardRoute
  '/cuet/study-plan/$duration': typeof CuetStudyPlanDurationRoute
  '/ipmat/admission/$institute': typeof IpmatAdmissionInstituteRoute
  '/ipmat/city/$city': typeof IpmatCityCityRoute
  '/ipmat/colleges/$institute': typeof IpmatCollegesInstituteRoute
  '/ipmat/compare/indore-vs-rohtak': typeof IpmatCompareIndoreVsRohtakRoute
  '/ipmat/compare/ipm-vs-bba': typeof IpmatCompareIpmVsBbaRoute
  '/ipmat/composite-score/$institute': typeof IpmatCompositeScoreInstituteRoute
  '/ipmat/interview/$institute': typeof IpmatInterviewInstituteRoute
  '/ipmat/placements/$institute': typeof IpmatPlacementsInstituteRoute
  '/ipmat/preparation/$duration': typeof IpmatPreparationDurationRoute
  '/ipmat/programme/structure': typeof IpmatProgrammeStructureRoute
  '/ipmat/section-strategy/$section': typeof IpmatSectionStrategySectionRoute
  '/ipmat/syllabus/$section': typeof IpmatSyllabusSectionRoute
  '/cuet/admission/': typeof CuetAdmissionIndexRoute
  '/cuet/colleges/': typeof CuetCollegesIndexRoute
  '/cuet/compare/': typeof CuetCompareIndexRoute
  '/cuet/cutoff/': typeof CuetCutoffIndexRoute
  '/cuet/exam-centers/': typeof CuetExamCentersIndexRoute
  '/cuet/results/': typeof CuetResultsIndexRoute
  '/cuet/syllabus/': typeof CuetSyllabusIndexRoute
  '/ipmat/colleges/': typeof IpmatCollegesIndexRoute
  '/ipmat/compare/': typeof IpmatCompareIndexRoute
  '/ipmat/syllabus/': typeof IpmatSyllabusIndexRoute
  '/cuet/colleges/$university/$college': typeof CuetCollegesUniversityCollegeRoute
  '/cuet/colleges/best-for/$course': typeof CuetCollegesBestForCourseRoute
  '/cuet/cutoff/colleges-for/$band': typeof CuetCutoffCollegesForBandRoute
  '/ipmat/programme/$institute/fees': typeof IpmatProgrammeInstituteFeesRoute
  '/cuet/results/college-predictor/': typeof CuetResultsCollegePredictorIndexRoute
  '/cuet/cutoff/$university/$college/$course': typeof CuetCutoffUniversityCollegeCourseRoute
  '/cuet/results/college-predictor/$university/$course': typeof CuetResultsCollegePredictorUniversityCourseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/centres/$slug': typeof CentresSlugRoute
  '/courses/cuet': typeof CoursesCuetRoute
  '/courses/ipmat': typeof CoursesIpmatRoute
  '/cuet/admit-card': typeof CuetAdmitCardRoute
  '/cuet/changes': typeof CuetChangesRoute
  '/cuet/city-slip': typeof CuetCitySlipRoute
  '/cuet/coaching-in-delhi-ncr': typeof CuetCoachingInDelhiNcrRoute
  '/cuet/coaching-in-gtb-nagar': typeof CuetCoachingInGtbNagarRoute
  '/cuet/coaching-in-gurugram': typeof CuetCoachingInGurugramRoute
  '/cuet/coaching-in-hauz-khas': typeof CuetCoachingInHauzKhasRoute
  '/cuet/coaching-in-noida': typeof CuetCoachingInNoidaRoute
  '/cuet/eligibility': typeof CuetEligibilityRoute
  '/cuet/exam-day': typeof CuetExamDayRoute
  '/cuet/exam-pattern': typeof CuetExamPatternRoute
  '/cuet/faq': typeof CuetFaqRoute
  '/cuet/history': typeof CuetHistoryRoute
  '/cuet/is-cuet-hard': typeof CuetIsCuetHardRoute
  '/cuet/languages': typeof CuetLanguagesRoute
  '/cuet/marking': typeof CuetMarkingRoute
  '/cuet/parents-guide': typeof CuetParentsGuideRoute
  '/cuet/policy': typeof CuetPolicyRoute
  '/cuet/subject-rules': typeof CuetSubjectRulesRoute
  '/cuet/toppers': typeof CuetToppersRoute
  '/cuet/without-coaching': typeof CuetWithoutCoachingRoute
  '/faculty/$slug': typeof FacultySlugRoute
  '/faq/cuet': typeof FaqCuetRoute
  '/faq/ipmat': typeof FaqIpmatRoute
  '/ipmat/application-process': typeof IpmatApplicationProcessRoute
  '/ipmat/books-mocks': typeof IpmatBooksMocksRoute
  '/ipmat/campus-life': typeof IpmatCampusLifeRoute
  '/ipmat/coaching-in-delhi-ncr': typeof IpmatCoachingInDelhiNcrRoute
  '/ipmat/coaching-in-gtb-nagar': typeof IpmatCoachingInGtbNagarRoute
  '/ipmat/coaching-in-gurugram': typeof IpmatCoachingInGurugramRoute
  '/ipmat/coaching-in-hauz-khas': typeof IpmatCoachingInHauzKhasRoute
  '/ipmat/coaching-in-noida': typeof IpmatCoachingInNoidaRoute
  '/ipmat/cutoff': typeof IpmatCutoffRoute
  '/ipmat/eligibility': typeof IpmatEligibilityRoute
  '/ipmat/exam': typeof IpmatExamRoute
  '/ipmat/faq': typeof IpmatFaqRoute
  '/ipmat/important-dates': typeof IpmatImportantDatesRoute
  '/ipmat/marking-scheme': typeof IpmatMarkingSchemeRoute
  '/ipmat/parents-guide': typeof IpmatParentsGuideRoute
  '/ipmat/profile-building': typeof IpmatProfileBuildingRoute
  '/ipmat/roi': typeof IpmatRoiRoute
  '/ipmat/safe-score': typeof IpmatSafeScoreRoute
  '/ipmat/sectional-lock': typeof IpmatSectionalLockRoute
  '/ipmat/self-study-vs-coaching': typeof IpmatSelfStudyVsCoachingRoute
  '/ipmat/wat': typeof IpmatWatRoute
  '/ipmat/wellbeing': typeof IpmatWellbeingRoute
  '/ipmat/worth-it': typeof IpmatWorthItRoute
  '/blog': typeof BlogIndexRoute
  '/centres': typeof CentresIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/cuet': typeof CuetIndexRoute
  '/faculty': typeof FacultyIndexRoute
  '/faq': typeof FaqIndexRoute
  '/ipmat': typeof IpmatIndexRoute
  '/cuet/admission/freeze-vs-upgrade': typeof CuetAdmissionFreezeVsUpgradeRoute
  '/cuet/admission/spot-round': typeof CuetAdmissionSpotRoundRoute
  '/cuet/compare/$matchup': typeof CuetCompareMatchupRoute
  '/cuet/compare/cuet-vs-ipmat': typeof CuetCompareCuetVsIpmatRoute
  '/cuet/compare/quiz': typeof CuetCompareQuizRoute
  '/cuet/cutoff/dataset': typeof CuetCutoffDatasetRoute
  '/cuet/cutoff/how-cutoffs-work': typeof CuetCutoffHowCutoffsWorkRoute
  '/cuet/exam-centers/$city': typeof CuetExamCentersCityRoute
  '/cuet/news/$slug': typeof CuetNewsSlugRoute
  '/cuet/results/marks-vs-percentile': typeof CuetResultsMarksVsPercentileRoute
  '/cuet/results/normalization': typeof CuetResultsNormalizationRoute
  '/cuet/results/score-calculator': typeof CuetResultsScoreCalculatorRoute
  '/cuet/results/scorecard': typeof CuetResultsScorecardRoute
  '/cuet/study-plan/$duration': typeof CuetStudyPlanDurationRoute
  '/ipmat/admission/$institute': typeof IpmatAdmissionInstituteRoute
  '/ipmat/city/$city': typeof IpmatCityCityRoute
  '/ipmat/colleges/$institute': typeof IpmatCollegesInstituteRoute
  '/ipmat/compare/indore-vs-rohtak': typeof IpmatCompareIndoreVsRohtakRoute
  '/ipmat/compare/ipm-vs-bba': typeof IpmatCompareIpmVsBbaRoute
  '/ipmat/composite-score/$institute': typeof IpmatCompositeScoreInstituteRoute
  '/ipmat/interview/$institute': typeof IpmatInterviewInstituteRoute
  '/ipmat/placements/$institute': typeof IpmatPlacementsInstituteRoute
  '/ipmat/preparation/$duration': typeof IpmatPreparationDurationRoute
  '/ipmat/programme/structure': typeof IpmatProgrammeStructureRoute
  '/ipmat/section-strategy/$section': typeof IpmatSectionStrategySectionRoute
  '/ipmat/syllabus/$section': typeof IpmatSyllabusSectionRoute
  '/cuet/admission': typeof CuetAdmissionIndexRoute
  '/cuet/colleges': typeof CuetCollegesIndexRoute
  '/cuet/compare': typeof CuetCompareIndexRoute
  '/cuet/cutoff': typeof CuetCutoffIndexRoute
  '/cuet/exam-centers': typeof CuetExamCentersIndexRoute
  '/cuet/results': typeof CuetResultsIndexRoute
  '/cuet/syllabus': typeof CuetSyllabusIndexRoute
  '/ipmat/colleges': typeof IpmatCollegesIndexRoute
  '/ipmat/compare': typeof IpmatCompareIndexRoute
  '/ipmat/syllabus': typeof IpmatSyllabusIndexRoute
  '/cuet/colleges/$university/$college': typeof CuetCollegesUniversityCollegeRoute
  '/cuet/colleges/best-for/$course': typeof CuetCollegesBestForCourseRoute
  '/cuet/cutoff/colleges-for/$band': typeof CuetCutoffCollegesForBandRoute
  '/ipmat/programme/$institute/fees': typeof IpmatProgrammeInstituteFeesRoute
  '/cuet/results/college-predictor': typeof CuetResultsCollegePredictorIndexRoute
  '/cuet/cutoff/$university/$college/$course': typeof CuetCutoffUniversityCollegeCourseRoute
  '/cuet/results/college-predictor/$university/$course': typeof CuetResultsCollegePredictorUniversityCourseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/centres/$slug': typeof CentresSlugRoute
  '/courses/cuet': typeof CoursesCuetRoute
  '/courses/ipmat': typeof CoursesIpmatRoute
  '/cuet/admit-card': typeof CuetAdmitCardRoute
  '/cuet/changes': typeof CuetChangesRoute
  '/cuet/city-slip': typeof CuetCitySlipRoute
  '/cuet/coaching-in-delhi-ncr': typeof CuetCoachingInDelhiNcrRoute
  '/cuet/coaching-in-gtb-nagar': typeof CuetCoachingInGtbNagarRoute
  '/cuet/coaching-in-gurugram': typeof CuetCoachingInGurugramRoute
  '/cuet/coaching-in-hauz-khas': typeof CuetCoachingInHauzKhasRoute
  '/cuet/coaching-in-noida': typeof CuetCoachingInNoidaRoute
  '/cuet/eligibility': typeof CuetEligibilityRoute
  '/cuet/exam-day': typeof CuetExamDayRoute
  '/cuet/exam-pattern': typeof CuetExamPatternRoute
  '/cuet/faq': typeof CuetFaqRoute
  '/cuet/history': typeof CuetHistoryRoute
  '/cuet/is-cuet-hard': typeof CuetIsCuetHardRoute
  '/cuet/languages': typeof CuetLanguagesRoute
  '/cuet/marking': typeof CuetMarkingRoute
  '/cuet/parents-guide': typeof CuetParentsGuideRoute
  '/cuet/policy': typeof CuetPolicyRoute
  '/cuet/subject-rules': typeof CuetSubjectRulesRoute
  '/cuet/toppers': typeof CuetToppersRoute
  '/cuet/without-coaching': typeof CuetWithoutCoachingRoute
  '/faculty/$slug': typeof FacultySlugRoute
  '/faq/cuet': typeof FaqCuetRoute
  '/faq/ipmat': typeof FaqIpmatRoute
  '/ipmat/application-process': typeof IpmatApplicationProcessRoute
  '/ipmat/books-mocks': typeof IpmatBooksMocksRoute
  '/ipmat/campus-life': typeof IpmatCampusLifeRoute
  '/ipmat/coaching-in-delhi-ncr': typeof IpmatCoachingInDelhiNcrRoute
  '/ipmat/coaching-in-gtb-nagar': typeof IpmatCoachingInGtbNagarRoute
  '/ipmat/coaching-in-gurugram': typeof IpmatCoachingInGurugramRoute
  '/ipmat/coaching-in-hauz-khas': typeof IpmatCoachingInHauzKhasRoute
  '/ipmat/coaching-in-noida': typeof IpmatCoachingInNoidaRoute
  '/ipmat/cutoff': typeof IpmatCutoffRoute
  '/ipmat/eligibility': typeof IpmatEligibilityRoute
  '/ipmat/exam': typeof IpmatExamRoute
  '/ipmat/faq': typeof IpmatFaqRoute
  '/ipmat/important-dates': typeof IpmatImportantDatesRoute
  '/ipmat/marking-scheme': typeof IpmatMarkingSchemeRoute
  '/ipmat/parents-guide': typeof IpmatParentsGuideRoute
  '/ipmat/profile-building': typeof IpmatProfileBuildingRoute
  '/ipmat/roi': typeof IpmatRoiRoute
  '/ipmat/safe-score': typeof IpmatSafeScoreRoute
  '/ipmat/sectional-lock': typeof IpmatSectionalLockRoute
  '/ipmat/self-study-vs-coaching': typeof IpmatSelfStudyVsCoachingRoute
  '/ipmat/wat': typeof IpmatWatRoute
  '/ipmat/wellbeing': typeof IpmatWellbeingRoute
  '/ipmat/worth-it': typeof IpmatWorthItRoute
  '/blog/': typeof BlogIndexRoute
  '/centres/': typeof CentresIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/cuet/': typeof CuetIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/faq/': typeof FaqIndexRoute
  '/ipmat/': typeof IpmatIndexRoute
  '/cuet/admission/freeze-vs-upgrade': typeof CuetAdmissionFreezeVsUpgradeRoute
  '/cuet/admission/spot-round': typeof CuetAdmissionSpotRoundRoute
  '/cuet/compare/$matchup': typeof CuetCompareMatchupRoute
  '/cuet/compare/cuet-vs-ipmat': typeof CuetCompareCuetVsIpmatRoute
  '/cuet/compare/quiz': typeof CuetCompareQuizRoute
  '/cuet/cutoff/dataset': typeof CuetCutoffDatasetRoute
  '/cuet/cutoff/how-cutoffs-work': typeof CuetCutoffHowCutoffsWorkRoute
  '/cuet/exam-centers/$city': typeof CuetExamCentersCityRoute
  '/cuet/news/$slug': typeof CuetNewsSlugRoute
  '/cuet/results/marks-vs-percentile': typeof CuetResultsMarksVsPercentileRoute
  '/cuet/results/normalization': typeof CuetResultsNormalizationRoute
  '/cuet/results/score-calculator': typeof CuetResultsScoreCalculatorRoute
  '/cuet/results/scorecard': typeof CuetResultsScorecardRoute
  '/cuet/study-plan/$duration': typeof CuetStudyPlanDurationRoute
  '/ipmat/admission/$institute': typeof IpmatAdmissionInstituteRoute
  '/ipmat/city/$city': typeof IpmatCityCityRoute
  '/ipmat/colleges/$institute': typeof IpmatCollegesInstituteRoute
  '/ipmat/compare/indore-vs-rohtak': typeof IpmatCompareIndoreVsRohtakRoute
  '/ipmat/compare/ipm-vs-bba': typeof IpmatCompareIpmVsBbaRoute
  '/ipmat/composite-score/$institute': typeof IpmatCompositeScoreInstituteRoute
  '/ipmat/interview/$institute': typeof IpmatInterviewInstituteRoute
  '/ipmat/placements/$institute': typeof IpmatPlacementsInstituteRoute
  '/ipmat/preparation/$duration': typeof IpmatPreparationDurationRoute
  '/ipmat/programme/structure': typeof IpmatProgrammeStructureRoute
  '/ipmat/section-strategy/$section': typeof IpmatSectionStrategySectionRoute
  '/ipmat/syllabus/$section': typeof IpmatSyllabusSectionRoute
  '/cuet/admission/': typeof CuetAdmissionIndexRoute
  '/cuet/colleges/': typeof CuetCollegesIndexRoute
  '/cuet/compare/': typeof CuetCompareIndexRoute
  '/cuet/cutoff/': typeof CuetCutoffIndexRoute
  '/cuet/exam-centers/': typeof CuetExamCentersIndexRoute
  '/cuet/results/': typeof CuetResultsIndexRoute
  '/cuet/syllabus/': typeof CuetSyllabusIndexRoute
  '/ipmat/colleges/': typeof IpmatCollegesIndexRoute
  '/ipmat/compare/': typeof IpmatCompareIndexRoute
  '/ipmat/syllabus/': typeof IpmatSyllabusIndexRoute
  '/cuet/colleges/$university/$college': typeof CuetCollegesUniversityCollegeRoute
  '/cuet/colleges/best-for/$course': typeof CuetCollegesBestForCourseRoute
  '/cuet/cutoff/colleges-for/$band': typeof CuetCutoffCollegesForBandRoute
  '/ipmat/programme/$institute/fees': typeof IpmatProgrammeInstituteFeesRoute
  '/cuet/results/college-predictor/': typeof CuetResultsCollegePredictorIndexRoute
  '/cuet/cutoff/$university/$college/$course': typeof CuetCutoffUniversityCollegeCourseRoute
  '/cuet/results/college-predictor/$university/$course': typeof CuetResultsCollegePredictorUniversityCourseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/news'
    | '/privacy'
    | '/resources'
    | '/results'
    | '/sitemap'
    | '/terms'
    | '/blog/$slug'
    | '/centres/$slug'
    | '/courses/cuet'
    | '/courses/ipmat'
    | '/cuet/admit-card'
    | '/cuet/changes'
    | '/cuet/city-slip'
    | '/cuet/coaching-in-delhi-ncr'
    | '/cuet/coaching-in-gtb-nagar'
    | '/cuet/coaching-in-gurugram'
    | '/cuet/coaching-in-hauz-khas'
    | '/cuet/coaching-in-noida'
    | '/cuet/eligibility'
    | '/cuet/exam-day'
    | '/cuet/exam-pattern'
    | '/cuet/faq'
    | '/cuet/history'
    | '/cuet/is-cuet-hard'
    | '/cuet/languages'
    | '/cuet/marking'
    | '/cuet/parents-guide'
    | '/cuet/policy'
    | '/cuet/subject-rules'
    | '/cuet/toppers'
    | '/cuet/without-coaching'
    | '/faculty/$slug'
    | '/faq/cuet'
    | '/faq/ipmat'
    | '/ipmat/application-process'
    | '/ipmat/books-mocks'
    | '/ipmat/campus-life'
    | '/ipmat/coaching-in-delhi-ncr'
    | '/ipmat/coaching-in-gtb-nagar'
    | '/ipmat/coaching-in-gurugram'
    | '/ipmat/coaching-in-hauz-khas'
    | '/ipmat/coaching-in-noida'
    | '/ipmat/cutoff'
    | '/ipmat/eligibility'
    | '/ipmat/exam'
    | '/ipmat/faq'
    | '/ipmat/important-dates'
    | '/ipmat/marking-scheme'
    | '/ipmat/parents-guide'
    | '/ipmat/profile-building'
    | '/ipmat/roi'
    | '/ipmat/safe-score'
    | '/ipmat/sectional-lock'
    | '/ipmat/self-study-vs-coaching'
    | '/ipmat/wat'
    | '/ipmat/wellbeing'
    | '/ipmat/worth-it'
    | '/blog/'
    | '/centres/'
    | '/courses/'
    | '/cuet/'
    | '/faculty/'
    | '/faq/'
    | '/ipmat/'
    | '/cuet/admission/freeze-vs-upgrade'
    | '/cuet/admission/spot-round'
    | '/cuet/compare/$matchup'
    | '/cuet/compare/cuet-vs-ipmat'
    | '/cuet/compare/quiz'
    | '/cuet/cutoff/dataset'
    | '/cuet/cutoff/how-cutoffs-work'
    | '/cuet/exam-centers/$city'
    | '/cuet/news/$slug'
    | '/cuet/results/marks-vs-percentile'
    | '/cuet/results/normalization'
    | '/cuet/results/score-calculator'
    | '/cuet/results/scorecard'
    | '/cuet/study-plan/$duration'
    | '/ipmat/admission/$institute'
    | '/ipmat/city/$city'
    | '/ipmat/colleges/$institute'
    | '/ipmat/compare/indore-vs-rohtak'
    | '/ipmat/compare/ipm-vs-bba'
    | '/ipmat/composite-score/$institute'
    | '/ipmat/interview/$institute'
    | '/ipmat/placements/$institute'
    | '/ipmat/preparation/$duration'
    | '/ipmat/programme/structure'
    | '/ipmat/section-strategy/$section'
    | '/ipmat/syllabus/$section'
    | '/cuet/admission/'
    | '/cuet/colleges/'
    | '/cuet/compare/'
    | '/cuet/cutoff/'
    | '/cuet/exam-centers/'
    | '/cuet/results/'
    | '/cuet/syllabus/'
    | '/ipmat/colleges/'
    | '/ipmat/compare/'
    | '/ipmat/syllabus/'
    | '/cuet/colleges/$university/$college'
    | '/cuet/colleges/best-for/$course'
    | '/cuet/cutoff/colleges-for/$band'
    | '/ipmat/programme/$institute/fees'
    | '/cuet/results/college-predictor/'
    | '/cuet/cutoff/$university/$college/$course'
    | '/cuet/results/college-predictor/$university/$course'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/news'
    | '/privacy'
    | '/resources'
    | '/results'
    | '/sitemap'
    | '/terms'
    | '/blog/$slug'
    | '/centres/$slug'
    | '/courses/cuet'
    | '/courses/ipmat'
    | '/cuet/admit-card'
    | '/cuet/changes'
    | '/cuet/city-slip'
    | '/cuet/coaching-in-delhi-ncr'
    | '/cuet/coaching-in-gtb-nagar'
    | '/cuet/coaching-in-gurugram'
    | '/cuet/coaching-in-hauz-khas'
    | '/cuet/coaching-in-noida'
    | '/cuet/eligibility'
    | '/cuet/exam-day'
    | '/cuet/exam-pattern'
    | '/cuet/faq'
    | '/cuet/history'
    | '/cuet/is-cuet-hard'
    | '/cuet/languages'
    | '/cuet/marking'
    | '/cuet/parents-guide'
    | '/cuet/policy'
    | '/cuet/subject-rules'
    | '/cuet/toppers'
    | '/cuet/without-coaching'
    | '/faculty/$slug'
    | '/faq/cuet'
    | '/faq/ipmat'
    | '/ipmat/application-process'
    | '/ipmat/books-mocks'
    | '/ipmat/campus-life'
    | '/ipmat/coaching-in-delhi-ncr'
    | '/ipmat/coaching-in-gtb-nagar'
    | '/ipmat/coaching-in-gurugram'
    | '/ipmat/coaching-in-hauz-khas'
    | '/ipmat/coaching-in-noida'
    | '/ipmat/cutoff'
    | '/ipmat/eligibility'
    | '/ipmat/exam'
    | '/ipmat/faq'
    | '/ipmat/important-dates'
    | '/ipmat/marking-scheme'
    | '/ipmat/parents-guide'
    | '/ipmat/profile-building'
    | '/ipmat/roi'
    | '/ipmat/safe-score'
    | '/ipmat/sectional-lock'
    | '/ipmat/self-study-vs-coaching'
    | '/ipmat/wat'
    | '/ipmat/wellbeing'
    | '/ipmat/worth-it'
    | '/blog'
    | '/centres'
    | '/courses'
    | '/cuet'
    | '/faculty'
    | '/faq'
    | '/ipmat'
    | '/cuet/admission/freeze-vs-upgrade'
    | '/cuet/admission/spot-round'
    | '/cuet/compare/$matchup'
    | '/cuet/compare/cuet-vs-ipmat'
    | '/cuet/compare/quiz'
    | '/cuet/cutoff/dataset'
    | '/cuet/cutoff/how-cutoffs-work'
    | '/cuet/exam-centers/$city'
    | '/cuet/news/$slug'
    | '/cuet/results/marks-vs-percentile'
    | '/cuet/results/normalization'
    | '/cuet/results/score-calculator'
    | '/cuet/results/scorecard'
    | '/cuet/study-plan/$duration'
    | '/ipmat/admission/$institute'
    | '/ipmat/city/$city'
    | '/ipmat/colleges/$institute'
    | '/ipmat/compare/indore-vs-rohtak'
    | '/ipmat/compare/ipm-vs-bba'
    | '/ipmat/composite-score/$institute'
    | '/ipmat/interview/$institute'
    | '/ipmat/placements/$institute'
    | '/ipmat/preparation/$duration'
    | '/ipmat/programme/structure'
    | '/ipmat/section-strategy/$section'
    | '/ipmat/syllabus/$section'
    | '/cuet/admission'
    | '/cuet/colleges'
    | '/cuet/compare'
    | '/cuet/cutoff'
    | '/cuet/exam-centers'
    | '/cuet/results'
    | '/cuet/syllabus'
    | '/ipmat/colleges'
    | '/ipmat/compare'
    | '/ipmat/syllabus'
    | '/cuet/colleges/$university/$college'
    | '/cuet/colleges/best-for/$course'
    | '/cuet/cutoff/colleges-for/$band'
    | '/ipmat/programme/$institute/fees'
    | '/cuet/results/college-predictor'
    | '/cuet/cutoff/$university/$college/$course'
    | '/cuet/results/college-predictor/$university/$course'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/news'
    | '/privacy'
    | '/resources'
    | '/results'
    | '/sitemap'
    | '/terms'
    | '/blog/$slug'
    | '/centres/$slug'
    | '/courses/cuet'
    | '/courses/ipmat'
    | '/cuet/admit-card'
    | '/cuet/changes'
    | '/cuet/city-slip'
    | '/cuet/coaching-in-delhi-ncr'
    | '/cuet/coaching-in-gtb-nagar'
    | '/cuet/coaching-in-gurugram'
    | '/cuet/coaching-in-hauz-khas'
    | '/cuet/coaching-in-noida'
    | '/cuet/eligibility'
    | '/cuet/exam-day'
    | '/cuet/exam-pattern'
    | '/cuet/faq'
    | '/cuet/history'
    | '/cuet/is-cuet-hard'
    | '/cuet/languages'
    | '/cuet/marking'
    | '/cuet/parents-guide'
    | '/cuet/policy'
    | '/cuet/subject-rules'
    | '/cuet/toppers'
    | '/cuet/without-coaching'
    | '/faculty/$slug'
    | '/faq/cuet'
    | '/faq/ipmat'
    | '/ipmat/application-process'
    | '/ipmat/books-mocks'
    | '/ipmat/campus-life'
    | '/ipmat/coaching-in-delhi-ncr'
    | '/ipmat/coaching-in-gtb-nagar'
    | '/ipmat/coaching-in-gurugram'
    | '/ipmat/coaching-in-hauz-khas'
    | '/ipmat/coaching-in-noida'
    | '/ipmat/cutoff'
    | '/ipmat/eligibility'
    | '/ipmat/exam'
    | '/ipmat/faq'
    | '/ipmat/important-dates'
    | '/ipmat/marking-scheme'
    | '/ipmat/parents-guide'
    | '/ipmat/profile-building'
    | '/ipmat/roi'
    | '/ipmat/safe-score'
    | '/ipmat/sectional-lock'
    | '/ipmat/self-study-vs-coaching'
    | '/ipmat/wat'
    | '/ipmat/wellbeing'
    | '/ipmat/worth-it'
    | '/blog/'
    | '/centres/'
    | '/courses/'
    | '/cuet/'
    | '/faculty/'
    | '/faq/'
    | '/ipmat/'
    | '/cuet/admission/freeze-vs-upgrade'
    | '/cuet/admission/spot-round'
    | '/cuet/compare/$matchup'
    | '/cuet/compare/cuet-vs-ipmat'
    | '/cuet/compare/quiz'
    | '/cuet/cutoff/dataset'
    | '/cuet/cutoff/how-cutoffs-work'
    | '/cuet/exam-centers/$city'
    | '/cuet/news/$slug'
    | '/cuet/results/marks-vs-percentile'
    | '/cuet/results/normalization'
    | '/cuet/results/score-calculator'
    | '/cuet/results/scorecard'
    | '/cuet/study-plan/$duration'
    | '/ipmat/admission/$institute'
    | '/ipmat/city/$city'
    | '/ipmat/colleges/$institute'
    | '/ipmat/compare/indore-vs-rohtak'
    | '/ipmat/compare/ipm-vs-bba'
    | '/ipmat/composite-score/$institute'
    | '/ipmat/interview/$institute'
    | '/ipmat/placements/$institute'
    | '/ipmat/preparation/$duration'
    | '/ipmat/programme/structure'
    | '/ipmat/section-strategy/$section'
    | '/ipmat/syllabus/$section'
    | '/cuet/admission/'
    | '/cuet/colleges/'
    | '/cuet/compare/'
    | '/cuet/cutoff/'
    | '/cuet/exam-centers/'
    | '/cuet/results/'
    | '/cuet/syllabus/'
    | '/ipmat/colleges/'
    | '/ipmat/compare/'
    | '/ipmat/syllabus/'
    | '/cuet/colleges/$university/$college'
    | '/cuet/colleges/best-for/$course'
    | '/cuet/cutoff/colleges-for/$band'
    | '/ipmat/programme/$institute/fees'
    | '/cuet/results/college-predictor/'
    | '/cuet/cutoff/$university/$college/$course'
    | '/cuet/results/college-predictor/$university/$course'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  NewsRoute: typeof NewsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  ResultsRoute: typeof ResultsRoute
  SitemapRoute: typeof SitemapRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CentresSlugRoute: typeof CentresSlugRoute
  CoursesCuetRoute: typeof CoursesCuetRoute
  CoursesIpmatRoute: typeof CoursesIpmatRoute
  CuetAdmitCardRoute: typeof CuetAdmitCardRoute
  CuetChangesRoute: typeof CuetChangesRoute
  CuetCitySlipRoute: typeof CuetCitySlipRoute
  CuetCoachingInDelhiNcrRoute: typeof CuetCoachingInDelhiNcrRoute
  CuetCoachingInGtbNagarRoute: typeof CuetCoachingInGtbNagarRoute
  CuetCoachingInGurugramRoute: typeof CuetCoachingInGurugramRoute
  CuetCoachingInHauzKhasRoute: typeof CuetCoachingInHauzKhasRoute
  CuetCoachingInNoidaRoute: typeof CuetCoachingInNoidaRoute
  CuetEligibilityRoute: typeof CuetEligibilityRoute
  CuetExamDayRoute: typeof CuetExamDayRoute
  CuetExamPatternRoute: typeof CuetExamPatternRoute
  CuetFaqRoute: typeof CuetFaqRoute
  CuetHistoryRoute: typeof CuetHistoryRoute
  CuetIsCuetHardRoute: typeof CuetIsCuetHardRoute
  CuetLanguagesRoute: typeof CuetLanguagesRoute
  CuetMarkingRoute: typeof CuetMarkingRoute
  CuetParentsGuideRoute: typeof CuetParentsGuideRoute
  CuetPolicyRoute: typeof CuetPolicyRoute
  CuetSubjectRulesRoute: typeof CuetSubjectRulesRoute
  CuetToppersRoute: typeof CuetToppersRoute
  CuetWithoutCoachingRoute: typeof CuetWithoutCoachingRoute
  FacultySlugRoute: typeof FacultySlugRoute
  FaqCuetRoute: typeof FaqCuetRoute
  FaqIpmatRoute: typeof FaqIpmatRoute
  IpmatApplicationProcessRoute: typeof IpmatApplicationProcessRoute
  IpmatBooksMocksRoute: typeof IpmatBooksMocksRoute
  IpmatCampusLifeRoute: typeof IpmatCampusLifeRoute
  IpmatCoachingInDelhiNcrRoute: typeof IpmatCoachingInDelhiNcrRoute
  IpmatCoachingInGtbNagarRoute: typeof IpmatCoachingInGtbNagarRoute
  IpmatCoachingInGurugramRoute: typeof IpmatCoachingInGurugramRoute
  IpmatCoachingInHauzKhasRoute: typeof IpmatCoachingInHauzKhasRoute
  IpmatCoachingInNoidaRoute: typeof IpmatCoachingInNoidaRoute
  IpmatCutoffRoute: typeof IpmatCutoffRoute
  IpmatEligibilityRoute: typeof IpmatEligibilityRoute
  IpmatExamRoute: typeof IpmatExamRoute
  IpmatFaqRoute: typeof IpmatFaqRoute
  IpmatImportantDatesRoute: typeof IpmatImportantDatesRoute
  IpmatMarkingSchemeRoute: typeof IpmatMarkingSchemeRoute
  IpmatParentsGuideRoute: typeof IpmatParentsGuideRoute
  IpmatProfileBuildingRoute: typeof IpmatProfileBuildingRoute
  IpmatRoiRoute: typeof IpmatRoiRoute
  IpmatSafeScoreRoute: typeof IpmatSafeScoreRoute
  IpmatSectionalLockRoute: typeof IpmatSectionalLockRoute
  IpmatSelfStudyVsCoachingRoute: typeof IpmatSelfStudyVsCoachingRoute
  IpmatWatRoute: typeof IpmatWatRoute
  IpmatWellbeingRoute: typeof IpmatWellbeingRoute
  IpmatWorthItRoute: typeof IpmatWorthItRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CentresIndexRoute: typeof CentresIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  CuetIndexRoute: typeof CuetIndexRoute
  FacultyIndexRoute: typeof FacultyIndexRoute
  FaqIndexRoute: typeof FaqIndexRoute
  IpmatIndexRoute: typeof IpmatIndexRoute
  CuetAdmissionFreezeVsUpgradeRoute: typeof CuetAdmissionFreezeVsUpgradeRoute
  CuetAdmissionSpotRoundRoute: typeof CuetAdmissionSpotRoundRoute
  CuetCompareMatchupRoute: typeof CuetCompareMatchupRoute
  CuetCompareCuetVsIpmatRoute: typeof CuetCompareCuetVsIpmatRoute
  CuetCompareQuizRoute: typeof CuetCompareQuizRoute
  CuetCutoffDatasetRoute: typeof CuetCutoffDatasetRoute
  CuetCutoffHowCutoffsWorkRoute: typeof CuetCutoffHowCutoffsWorkRoute
  CuetExamCentersCityRoute: typeof CuetExamCentersCityRoute
  CuetNewsSlugRoute: typeof CuetNewsSlugRoute
  CuetResultsMarksVsPercentileRoute: typeof CuetResultsMarksVsPercentileRoute
  CuetResultsNormalizationRoute: typeof CuetResultsNormalizationRoute
  CuetResultsScoreCalculatorRoute: typeof CuetResultsScoreCalculatorRoute
  CuetResultsScorecardRoute: typeof CuetResultsScorecardRoute
  CuetStudyPlanDurationRoute: typeof CuetStudyPlanDurationRoute
  IpmatAdmissionInstituteRoute: typeof IpmatAdmissionInstituteRoute
  IpmatCityCityRoute: typeof IpmatCityCityRoute
  IpmatCollegesInstituteRoute: typeof IpmatCollegesInstituteRoute
  IpmatCompareIndoreVsRohtakRoute: typeof IpmatCompareIndoreVsRohtakRoute
  IpmatCompareIpmVsBbaRoute: typeof IpmatCompareIpmVsBbaRoute
  IpmatCompositeScoreInstituteRoute: typeof IpmatCompositeScoreInstituteRoute
  IpmatInterviewInstituteRoute: typeof IpmatInterviewInstituteRoute
  IpmatPlacementsInstituteRoute: typeof IpmatPlacementsInstituteRoute
  IpmatPreparationDurationRoute: typeof IpmatPreparationDurationRoute
  IpmatProgrammeStructureRoute: typeof IpmatProgrammeStructureRoute
  IpmatSectionStrategySectionRoute: typeof IpmatSectionStrategySectionRoute
  IpmatSyllabusSectionRoute: typeof IpmatSyllabusSectionRoute
  CuetAdmissionIndexRoute: typeof CuetAdmissionIndexRoute
  CuetCollegesIndexRoute: typeof CuetCollegesIndexRoute
  CuetCompareIndexRoute: typeof CuetCompareIndexRoute
  CuetCutoffIndexRoute: typeof CuetCutoffIndexRoute
  CuetExamCentersIndexRoute: typeof CuetExamCentersIndexRoute
  CuetResultsIndexRoute: typeof CuetResultsIndexRoute
  CuetSyllabusIndexRoute: typeof CuetSyllabusIndexRoute
  IpmatCollegesIndexRoute: typeof IpmatCollegesIndexRoute
  IpmatCompareIndexRoute: typeof IpmatCompareIndexRoute
  IpmatSyllabusIndexRoute: typeof IpmatSyllabusIndexRoute
  CuetCollegesUniversityCollegeRoute: typeof CuetCollegesUniversityCollegeRoute
  CuetCollegesBestForCourseRoute: typeof CuetCollegesBestForCourseRoute
  CuetCutoffCollegesForBandRoute: typeof CuetCutoffCollegesForBandRoute
  IpmatProgrammeInstituteFeesRoute: typeof IpmatProgrammeInstituteFeesRoute
  CuetResultsCollegePredictorIndexRoute: typeof CuetResultsCollegePredictorIndexRoute
  CuetCutoffUniversityCollegeCourseRoute: typeof CuetCutoffUniversityCollegeCourseRoute
  CuetResultsCollegePredictorUniversityCourseRoute: typeof CuetResultsCollegePredictorUniversityCourseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/': {
      id: '/ipmat/'
      path: '/ipmat'
      fullPath: '/ipmat/'
      preLoaderRoute: typeof IpmatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/': {
      id: '/faq/'
      path: '/faq'
      fullPath: '/faq/'
      preLoaderRoute: typeof FaqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/': {
      id: '/faculty/'
      path: '/faculty'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/': {
      id: '/cuet/'
      path: '/cuet'
      fullPath: '/cuet/'
      preLoaderRoute: typeof CuetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centres/': {
      id: '/centres/'
      path: '/centres'
      fullPath: '/centres/'
      preLoaderRoute: typeof CentresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/worth-it': {
      id: '/ipmat/worth-it'
      path: '/ipmat/worth-it'
      fullPath: '/ipmat/worth-it'
      preLoaderRoute: typeof IpmatWorthItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/wellbeing': {
      id: '/ipmat/wellbeing'
      path: '/ipmat/wellbeing'
      fullPath: '/ipmat/wellbeing'
      preLoaderRoute: typeof IpmatWellbeingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/wat': {
      id: '/ipmat/wat'
      path: '/ipmat/wat'
      fullPath: '/ipmat/wat'
      preLoaderRoute: typeof IpmatWatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/self-study-vs-coaching': {
      id: '/ipmat/self-study-vs-coaching'
      path: '/ipmat/self-study-vs-coaching'
      fullPath: '/ipmat/self-study-vs-coaching'
      preLoaderRoute: typeof IpmatSelfStudyVsCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/sectional-lock': {
      id: '/ipmat/sectional-lock'
      path: '/ipmat/sectional-lock'
      fullPath: '/ipmat/sectional-lock'
      preLoaderRoute: typeof IpmatSectionalLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/safe-score': {
      id: '/ipmat/safe-score'
      path: '/ipmat/safe-score'
      fullPath: '/ipmat/safe-score'
      preLoaderRoute: typeof IpmatSafeScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/roi': {
      id: '/ipmat/roi'
      path: '/ipmat/roi'
      fullPath: '/ipmat/roi'
      preLoaderRoute: typeof IpmatRoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/profile-building': {
      id: '/ipmat/profile-building'
      path: '/ipmat/profile-building'
      fullPath: '/ipmat/profile-building'
      preLoaderRoute: typeof IpmatProfileBuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/parents-guide': {
      id: '/ipmat/parents-guide'
      path: '/ipmat/parents-guide'
      fullPath: '/ipmat/parents-guide'
      preLoaderRoute: typeof IpmatParentsGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/marking-scheme': {
      id: '/ipmat/marking-scheme'
      path: '/ipmat/marking-scheme'
      fullPath: '/ipmat/marking-scheme'
      preLoaderRoute: typeof IpmatMarkingSchemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/important-dates': {
      id: '/ipmat/important-dates'
      path: '/ipmat/important-dates'
      fullPath: '/ipmat/important-dates'
      preLoaderRoute: typeof IpmatImportantDatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/faq': {
      id: '/ipmat/faq'
      path: '/ipmat/faq'
      fullPath: '/ipmat/faq'
      preLoaderRoute: typeof IpmatFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/exam': {
      id: '/ipmat/exam'
      path: '/ipmat/exam'
      fullPath: '/ipmat/exam'
      preLoaderRoute: typeof IpmatExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/eligibility': {
      id: '/ipmat/eligibility'
      path: '/ipmat/eligibility'
      fullPath: '/ipmat/eligibility'
      preLoaderRoute: typeof IpmatEligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/cutoff': {
      id: '/ipmat/cutoff'
      path: '/ipmat/cutoff'
      fullPath: '/ipmat/cutoff'
      preLoaderRoute: typeof IpmatCutoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/coaching-in-noida': {
      id: '/ipmat/coaching-in-noida'
      path: '/ipmat/coaching-in-noida'
      fullPath: '/ipmat/coaching-in-noida'
      preLoaderRoute: typeof IpmatCoachingInNoidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/coaching-in-hauz-khas': {
      id: '/ipmat/coaching-in-hauz-khas'
      path: '/ipmat/coaching-in-hauz-khas'
      fullPath: '/ipmat/coaching-in-hauz-khas'
      preLoaderRoute: typeof IpmatCoachingInHauzKhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/coaching-in-gurugram': {
      id: '/ipmat/coaching-in-gurugram'
      path: '/ipmat/coaching-in-gurugram'
      fullPath: '/ipmat/coaching-in-gurugram'
      preLoaderRoute: typeof IpmatCoachingInGurugramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/coaching-in-gtb-nagar': {
      id: '/ipmat/coaching-in-gtb-nagar'
      path: '/ipmat/coaching-in-gtb-nagar'
      fullPath: '/ipmat/coaching-in-gtb-nagar'
      preLoaderRoute: typeof IpmatCoachingInGtbNagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/coaching-in-delhi-ncr': {
      id: '/ipmat/coaching-in-delhi-ncr'
      path: '/ipmat/coaching-in-delhi-ncr'
      fullPath: '/ipmat/coaching-in-delhi-ncr'
      preLoaderRoute: typeof IpmatCoachingInDelhiNcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/campus-life': {
      id: '/ipmat/campus-life'
      path: '/ipmat/campus-life'
      fullPath: '/ipmat/campus-life'
      preLoaderRoute: typeof IpmatCampusLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/books-mocks': {
      id: '/ipmat/books-mocks'
      path: '/ipmat/books-mocks'
      fullPath: '/ipmat/books-mocks'
      preLoaderRoute: typeof IpmatBooksMocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/application-process': {
      id: '/ipmat/application-process'
      path: '/ipmat/application-process'
      fullPath: '/ipmat/application-process'
      preLoaderRoute: typeof IpmatApplicationProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/ipmat': {
      id: '/faq/ipmat'
      path: '/faq/ipmat'
      fullPath: '/faq/ipmat'
      preLoaderRoute: typeof FaqIpmatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/cuet': {
      id: '/faq/cuet'
      path: '/faq/cuet'
      fullPath: '/faq/cuet'
      preLoaderRoute: typeof FaqCuetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/$slug': {
      id: '/faculty/$slug'
      path: '/faculty/$slug'
      fullPath: '/faculty/$slug'
      preLoaderRoute: typeof FacultySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/without-coaching': {
      id: '/cuet/without-coaching'
      path: '/cuet/without-coaching'
      fullPath: '/cuet/without-coaching'
      preLoaderRoute: typeof CuetWithoutCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/toppers': {
      id: '/cuet/toppers'
      path: '/cuet/toppers'
      fullPath: '/cuet/toppers'
      preLoaderRoute: typeof CuetToppersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/subject-rules': {
      id: '/cuet/subject-rules'
      path: '/cuet/subject-rules'
      fullPath: '/cuet/subject-rules'
      preLoaderRoute: typeof CuetSubjectRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/policy': {
      id: '/cuet/policy'
      path: '/cuet/policy'
      fullPath: '/cuet/policy'
      preLoaderRoute: typeof CuetPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/parents-guide': {
      id: '/cuet/parents-guide'
      path: '/cuet/parents-guide'
      fullPath: '/cuet/parents-guide'
      preLoaderRoute: typeof CuetParentsGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/marking': {
      id: '/cuet/marking'
      path: '/cuet/marking'
      fullPath: '/cuet/marking'
      preLoaderRoute: typeof CuetMarkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/languages': {
      id: '/cuet/languages'
      path: '/cuet/languages'
      fullPath: '/cuet/languages'
      preLoaderRoute: typeof CuetLanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/is-cuet-hard': {
      id: '/cuet/is-cuet-hard'
      path: '/cuet/is-cuet-hard'
      fullPath: '/cuet/is-cuet-hard'
      preLoaderRoute: typeof CuetIsCuetHardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/history': {
      id: '/cuet/history'
      path: '/cuet/history'
      fullPath: '/cuet/history'
      preLoaderRoute: typeof CuetHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/faq': {
      id: '/cuet/faq'
      path: '/cuet/faq'
      fullPath: '/cuet/faq'
      preLoaderRoute: typeof CuetFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/exam-pattern': {
      id: '/cuet/exam-pattern'
      path: '/cuet/exam-pattern'
      fullPath: '/cuet/exam-pattern'
      preLoaderRoute: typeof CuetExamPatternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/exam-day': {
      id: '/cuet/exam-day'
      path: '/cuet/exam-day'
      fullPath: '/cuet/exam-day'
      preLoaderRoute: typeof CuetExamDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/eligibility': {
      id: '/cuet/eligibility'
      path: '/cuet/eligibility'
      fullPath: '/cuet/eligibility'
      preLoaderRoute: typeof CuetEligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/coaching-in-noida': {
      id: '/cuet/coaching-in-noida'
      path: '/cuet/coaching-in-noida'
      fullPath: '/cuet/coaching-in-noida'
      preLoaderRoute: typeof CuetCoachingInNoidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/coaching-in-hauz-khas': {
      id: '/cuet/coaching-in-hauz-khas'
      path: '/cuet/coaching-in-hauz-khas'
      fullPath: '/cuet/coaching-in-hauz-khas'
      preLoaderRoute: typeof CuetCoachingInHauzKhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/coaching-in-gurugram': {
      id: '/cuet/coaching-in-gurugram'
      path: '/cuet/coaching-in-gurugram'
      fullPath: '/cuet/coaching-in-gurugram'
      preLoaderRoute: typeof CuetCoachingInGurugramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/coaching-in-gtb-nagar': {
      id: '/cuet/coaching-in-gtb-nagar'
      path: '/cuet/coaching-in-gtb-nagar'
      fullPath: '/cuet/coaching-in-gtb-nagar'
      preLoaderRoute: typeof CuetCoachingInGtbNagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/coaching-in-delhi-ncr': {
      id: '/cuet/coaching-in-delhi-ncr'
      path: '/cuet/coaching-in-delhi-ncr'
      fullPath: '/cuet/coaching-in-delhi-ncr'
      preLoaderRoute: typeof CuetCoachingInDelhiNcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/city-slip': {
      id: '/cuet/city-slip'
      path: '/cuet/city-slip'
      fullPath: '/cuet/city-slip'
      preLoaderRoute: typeof CuetCitySlipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/changes': {
      id: '/cuet/changes'
      path: '/cuet/changes'
      fullPath: '/cuet/changes'
      preLoaderRoute: typeof CuetChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/admit-card': {
      id: '/cuet/admit-card'
      path: '/cuet/admit-card'
      fullPath: '/cuet/admit-card'
      preLoaderRoute: typeof CuetAdmitCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/ipmat': {
      id: '/courses/ipmat'
      path: '/courses/ipmat'
      fullPath: '/courses/ipmat'
      preLoaderRoute: typeof CoursesIpmatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/cuet': {
      id: '/courses/cuet'
      path: '/courses/cuet'
      fullPath: '/courses/cuet'
      preLoaderRoute: typeof CoursesCuetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centres/$slug': {
      id: '/centres/$slug'
      path: '/centres/$slug'
      fullPath: '/centres/$slug'
      preLoaderRoute: typeof CentresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/syllabus/': {
      id: '/ipmat/syllabus/'
      path: '/ipmat/syllabus'
      fullPath: '/ipmat/syllabus/'
      preLoaderRoute: typeof IpmatSyllabusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/compare/': {
      id: '/ipmat/compare/'
      path: '/ipmat/compare'
      fullPath: '/ipmat/compare/'
      preLoaderRoute: typeof IpmatCompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/colleges/': {
      id: '/ipmat/colleges/'
      path: '/ipmat/colleges'
      fullPath: '/ipmat/colleges/'
      preLoaderRoute: typeof IpmatCollegesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/syllabus/': {
      id: '/cuet/syllabus/'
      path: '/cuet/syllabus'
      fullPath: '/cuet/syllabus/'
      preLoaderRoute: typeof CuetSyllabusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/results/': {
      id: '/cuet/results/'
      path: '/cuet/results'
      fullPath: '/cuet/results/'
      preLoaderRoute: typeof CuetResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/exam-centers/': {
      id: '/cuet/exam-centers/'
      path: '/cuet/exam-centers'
      fullPath: '/cuet/exam-centers/'
      preLoaderRoute: typeof CuetExamCentersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/cutoff/': {
      id: '/cuet/cutoff/'
      path: '/cuet/cutoff'
      fullPath: '/cuet/cutoff/'
      preLoaderRoute: typeof CuetCutoffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/compare/': {
      id: '/cuet/compare/'
      path: '/cuet/compare'
      fullPath: '/cuet/compare/'
      preLoaderRoute: typeof CuetCompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/colleges/': {
      id: '/cuet/colleges/'
      path: '/cuet/colleges'
      fullPath: '/cuet/colleges/'
      preLoaderRoute: typeof CuetCollegesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/admission/': {
      id: '/cuet/admission/'
      path: '/cuet/admission'
      fullPath: '/cuet/admission/'
      preLoaderRoute: typeof CuetAdmissionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/syllabus/$section': {
      id: '/ipmat/syllabus/$section'
      path: '/ipmat/syllabus/$section'
      fullPath: '/ipmat/syllabus/$section'
      preLoaderRoute: typeof IpmatSyllabusSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/section-strategy/$section': {
      id: '/ipmat/section-strategy/$section'
      path: '/ipmat/section-strategy/$section'
      fullPath: '/ipmat/section-strategy/$section'
      preLoaderRoute: typeof IpmatSectionStrategySectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/programme/structure': {
      id: '/ipmat/programme/structure'
      path: '/ipmat/programme/structure'
      fullPath: '/ipmat/programme/structure'
      preLoaderRoute: typeof IpmatProgrammeStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/preparation/$duration': {
      id: '/ipmat/preparation/$duration'
      path: '/ipmat/preparation/$duration'
      fullPath: '/ipmat/preparation/$duration'
      preLoaderRoute: typeof IpmatPreparationDurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/placements/$institute': {
      id: '/ipmat/placements/$institute'
      path: '/ipmat/placements/$institute'
      fullPath: '/ipmat/placements/$institute'
      preLoaderRoute: typeof IpmatPlacementsInstituteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/interview/$institute': {
      id: '/ipmat/interview/$institute'
      path: '/ipmat/interview/$institute'
      fullPath: '/ipmat/interview/$institute'
      preLoaderRoute: typeof IpmatInterviewInstituteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/composite-score/$institute': {
      id: '/ipmat/composite-score/$institute'
      path: '/ipmat/composite-score/$institute'
      fullPath: '/ipmat/composite-score/$institute'
      preLoaderRoute: typeof IpmatCompositeScoreInstituteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/compare/ipm-vs-bba': {
      id: '/ipmat/compare/ipm-vs-bba'
      path: '/ipmat/compare/ipm-vs-bba'
      fullPath: '/ipmat/compare/ipm-vs-bba'
      preLoaderRoute: typeof IpmatCompareIpmVsBbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/compare/indore-vs-rohtak': {
      id: '/ipmat/compare/indore-vs-rohtak'
      path: '/ipmat/compare/indore-vs-rohtak'
      fullPath: '/ipmat/compare/indore-vs-rohtak'
      preLoaderRoute: typeof IpmatCompareIndoreVsRohtakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/colleges/$institute': {
      id: '/ipmat/colleges/$institute'
      path: '/ipmat/colleges/$institute'
      fullPath: '/ipmat/colleges/$institute'
      preLoaderRoute: typeof IpmatCollegesInstituteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/city/$city': {
      id: '/ipmat/city/$city'
      path: '/ipmat/city/$city'
      fullPath: '/ipmat/city/$city'
      preLoaderRoute: typeof IpmatCityCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/admission/$institute': {
      id: '/ipmat/admission/$institute'
      path: '/ipmat/admission/$institute'
      fullPath: '/ipmat/admission/$institute'
      preLoaderRoute: typeof IpmatAdmissionInstituteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/study-plan/$duration': {
      id: '/cuet/study-plan/$duration'
      path: '/cuet/study-plan/$duration'
      fullPath: '/cuet/study-plan/$duration'
      preLoaderRoute: typeof CuetStudyPlanDurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/results/scorecard': {
      id: '/cuet/results/scorecard'
      path: '/cuet/results/scorecard'
      fullPath: '/cuet/results/scorecard'
      preLoaderRoute: typeof CuetResultsScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/results/score-calculator': {
      id: '/cuet/results/score-calculator'
      path: '/cuet/results/score-calculator'
      fullPath: '/cuet/results/score-calculator'
      preLoaderRoute: typeof CuetResultsScoreCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/results/normalization': {
      id: '/cuet/results/normalization'
      path: '/cuet/results/normalization'
      fullPath: '/cuet/results/normalization'
      preLoaderRoute: typeof CuetResultsNormalizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/results/marks-vs-percentile': {
      id: '/cuet/results/marks-vs-percentile'
      path: '/cuet/results/marks-vs-percentile'
      fullPath: '/cuet/results/marks-vs-percentile'
      preLoaderRoute: typeof CuetResultsMarksVsPercentileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/news/$slug': {
      id: '/cuet/news/$slug'
      path: '/cuet/news/$slug'
      fullPath: '/cuet/news/$slug'
      preLoaderRoute: typeof CuetNewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/exam-centers/$city': {
      id: '/cuet/exam-centers/$city'
      path: '/cuet/exam-centers/$city'
      fullPath: '/cuet/exam-centers/$city'
      preLoaderRoute: typeof CuetExamCentersCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/cutoff/how-cutoffs-work': {
      id: '/cuet/cutoff/how-cutoffs-work'
      path: '/cuet/cutoff/how-cutoffs-work'
      fullPath: '/cuet/cutoff/how-cutoffs-work'
      preLoaderRoute: typeof CuetCutoffHowCutoffsWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/cutoff/dataset': {
      id: '/cuet/cutoff/dataset'
      path: '/cuet/cutoff/dataset'
      fullPath: '/cuet/cutoff/dataset'
      preLoaderRoute: typeof CuetCutoffDatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/compare/quiz': {
      id: '/cuet/compare/quiz'
      path: '/cuet/compare/quiz'
      fullPath: '/cuet/compare/quiz'
      preLoaderRoute: typeof CuetCompareQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/compare/cuet-vs-ipmat': {
      id: '/cuet/compare/cuet-vs-ipmat'
      path: '/cuet/compare/cuet-vs-ipmat'
      fullPath: '/cuet/compare/cuet-vs-ipmat'
      preLoaderRoute: typeof CuetCompareCuetVsIpmatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/compare/$matchup': {
      id: '/cuet/compare/$matchup'
      path: '/cuet/compare/$matchup'
      fullPath: '/cuet/compare/$matchup'
      preLoaderRoute: typeof CuetCompareMatchupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/admission/spot-round': {
      id: '/cuet/admission/spot-round'
      path: '/cuet/admission/spot-round'
      fullPath: '/cuet/admission/spot-round'
      preLoaderRoute: typeof CuetAdmissionSpotRoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/admission/freeze-vs-upgrade': {
      id: '/cuet/admission/freeze-vs-upgrade'
      path: '/cuet/admission/freeze-vs-upgrade'
      fullPath: '/cuet/admission/freeze-vs-upgrade'
      preLoaderRoute: typeof CuetAdmissionFreezeVsUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/results/college-predictor/': {
      id: '/cuet/results/college-predictor/'
      path: '/cuet/results/college-predictor'
      fullPath: '/cuet/results/college-predictor/'
      preLoaderRoute: typeof CuetResultsCollegePredictorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipmat/programme/$institute/fees': {
      id: '/ipmat/programme/$institute/fees'
      path: '/ipmat/programme/$institute/fees'
      fullPath: '/ipmat/programme/$institute/fees'
      preLoaderRoute: typeof IpmatProgrammeInstituteFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/cutoff/colleges-for/$band': {
      id: '/cuet/cutoff/colleges-for/$band'
      path: '/cuet/cutoff/colleges-for/$band'
      fullPath: '/cuet/cutoff/colleges-for/$band'
      preLoaderRoute: typeof CuetCutoffCollegesForBandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/colleges/best-for/$course': {
      id: '/cuet/colleges/best-for/$course'
      path: '/cuet/colleges/best-for/$course'
      fullPath: '/cuet/colleges/best-for/$course'
      preLoaderRoute: typeof CuetCollegesBestForCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/colleges/$university/$college': {
      id: '/cuet/colleges/$university/$college'
      path: '/cuet/colleges/$university/$college'
      fullPath: '/cuet/colleges/$university/$college'
      preLoaderRoute: typeof CuetCollegesUniversityCollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/results/college-predictor/$university/$course': {
      id: '/cuet/results/college-predictor/$university/$course'
      path: '/cuet/results/college-predictor/$university/$course'
      fullPath: '/cuet/results/college-predictor/$university/$course'
      preLoaderRoute: typeof CuetResultsCollegePredictorUniversityCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuet/cutoff/$university/$college/$course': {
      id: '/cuet/cutoff/$university/$college/$course'
      path: '/cuet/cutoff/$university/$college/$course'
      fullPath: '/cuet/cutoff/$university/$college/$course'
      preLoaderRoute: typeof CuetCutoffUniversityCollegeCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  NewsRoute: NewsRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  ResultsRoute: ResultsRoute,
  SitemapRoute: SitemapRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CentresSlugRoute: CentresSlugRoute,
  CoursesCuetRoute: CoursesCuetRoute,
  CoursesIpmatRoute: CoursesIpmatRoute,
  CuetAdmitCardRoute: CuetAdmitCardRoute,
  CuetChangesRoute: CuetChangesRoute,
  CuetCitySlipRoute: CuetCitySlipRoute,
  CuetCoachingInDelhiNcrRoute: CuetCoachingInDelhiNcrRoute,
  CuetCoachingInGtbNagarRoute: CuetCoachingInGtbNagarRoute,
  CuetCoachingInGurugramRoute: CuetCoachingInGurugramRoute,
  CuetCoachingInHauzKhasRoute: CuetCoachingInHauzKhasRoute,
  CuetCoachingInNoidaRoute: CuetCoachingInNoidaRoute,
  CuetEligibilityRoute: CuetEligibilityRoute,
  CuetExamDayRoute: CuetExamDayRoute,
  CuetExamPatternRoute: CuetExamPatternRoute,
  CuetFaqRoute: CuetFaqRoute,
  CuetHistoryRoute: CuetHistoryRoute,
  CuetIsCuetHardRoute: CuetIsCuetHardRoute,
  CuetLanguagesRoute: CuetLanguagesRoute,
  CuetMarkingRoute: CuetMarkingRoute,
  CuetParentsGuideRoute: CuetParentsGuideRoute,
  CuetPolicyRoute: CuetPolicyRoute,
  CuetSubjectRulesRoute: CuetSubjectRulesRoute,
  CuetToppersRoute: CuetToppersRoute,
  CuetWithoutCoachingRoute: CuetWithoutCoachingRoute,
  FacultySlugRoute: FacultySlugRoute,
  FaqCuetRoute: FaqCuetRoute,
  FaqIpmatRoute: FaqIpmatRoute,
  IpmatApplicationProcessRoute: IpmatApplicationProcessRoute,
  IpmatBooksMocksRoute: IpmatBooksMocksRoute,
  IpmatCampusLifeRoute: IpmatCampusLifeRoute,
  IpmatCoachingInDelhiNcrRoute: IpmatCoachingInDelhiNcrRoute,
  IpmatCoachingInGtbNagarRoute: IpmatCoachingInGtbNagarRoute,
  IpmatCoachingInGurugramRoute: IpmatCoachingInGurugramRoute,
  IpmatCoachingInHauzKhasRoute: IpmatCoachingInHauzKhasRoute,
  IpmatCoachingInNoidaRoute: IpmatCoachingInNoidaRoute,
  IpmatCutoffRoute: IpmatCutoffRoute,
  IpmatEligibilityRoute: IpmatEligibilityRoute,
  IpmatExamRoute: IpmatExamRoute,
  IpmatFaqRoute: IpmatFaqRoute,
  IpmatImportantDatesRoute: IpmatImportantDatesRoute,
  IpmatMarkingSchemeRoute: IpmatMarkingSchemeRoute,
  IpmatParentsGuideRoute: IpmatParentsGuideRoute,
  IpmatProfileBuildingRoute: IpmatProfileBuildingRoute,
  IpmatRoiRoute: IpmatRoiRoute,
  IpmatSafeScoreRoute: IpmatSafeScoreRoute,
  IpmatSectionalLockRoute: IpmatSectionalLockRoute,
  IpmatSelfStudyVsCoachingRoute: IpmatSelfStudyVsCoachingRoute,
  IpmatWatRoute: IpmatWatRoute,
  IpmatWellbeingRoute: IpmatWellbeingRoute,
  IpmatWorthItRoute: IpmatWorthItRoute,
  BlogIndexRoute: BlogIndexRoute,
  CentresIndexRoute: CentresIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  CuetIndexRoute: CuetIndexRoute,
  FacultyIndexRoute: FacultyIndexRoute,
  FaqIndexRoute: FaqIndexRoute,
  IpmatIndexRoute: IpmatIndexRoute,
  CuetAdmissionFreezeVsUpgradeRoute: CuetAdmissionFreezeVsUpgradeRoute,
  CuetAdmissionSpotRoundRoute: CuetAdmissionSpotRoundRoute,
  CuetCompareMatchupRoute: CuetCompareMatchupRoute,
  CuetCompareCuetVsIpmatRoute: CuetCompareCuetVsIpmatRoute,
  CuetCompareQuizRoute: CuetCompareQuizRoute,
  CuetCutoffDatasetRoute: CuetCutoffDatasetRoute,
  CuetCutoffHowCutoffsWorkRoute: CuetCutoffHowCutoffsWorkRoute,
  CuetExamCentersCityRoute: CuetExamCentersCityRoute,
  CuetNewsSlugRoute: CuetNewsSlugRoute,
  CuetResultsMarksVsPercentileRoute: CuetResultsMarksVsPercentileRoute,
  CuetResultsNormalizationRoute: CuetResultsNormalizationRoute,
  CuetResultsScoreCalculatorRoute: CuetResultsScoreCalculatorRoute,
  CuetResultsScorecardRoute: CuetResultsScorecardRoute,
  CuetStudyPlanDurationRoute: CuetStudyPlanDurationRoute,
  IpmatAdmissionInstituteRoute: IpmatAdmissionInstituteRoute,
  IpmatCityCityRoute: IpmatCityCityRoute,
  IpmatCollegesInstituteRoute: IpmatCollegesInstituteRoute,
  IpmatCompareIndoreVsRohtakRoute: IpmatCompareIndoreVsRohtakRoute,
  IpmatCompareIpmVsBbaRoute: IpmatCompareIpmVsBbaRoute,
  IpmatCompositeScoreInstituteRoute: IpmatCompositeScoreInstituteRoute,
  IpmatInterviewInstituteRoute: IpmatInterviewInstituteRoute,
  IpmatPlacementsInstituteRoute: IpmatPlacementsInstituteRoute,
  IpmatPreparationDurationRoute: IpmatPreparationDurationRoute,
  IpmatProgrammeStructureRoute: IpmatProgrammeStructureRoute,
  IpmatSectionStrategySectionRoute: IpmatSectionStrategySectionRoute,
  IpmatSyllabusSectionRoute: IpmatSyllabusSectionRoute,
  CuetAdmissionIndexRoute: CuetAdmissionIndexRoute,
  CuetCollegesIndexRoute: CuetCollegesIndexRoute,
  CuetCompareIndexRoute: CuetCompareIndexRoute,
  CuetCutoffIndexRoute: CuetCutoffIndexRoute,
  CuetExamCentersIndexRoute: CuetExamCentersIndexRoute,
  CuetResultsIndexRoute: CuetResultsIndexRoute,
  CuetSyllabusIndexRoute: CuetSyllabusIndexRoute,
  IpmatCollegesIndexRoute: IpmatCollegesIndexRoute,
  IpmatCompareIndexRoute: IpmatCompareIndexRoute,
  IpmatSyllabusIndexRoute: IpmatSyllabusIndexRoute,
  CuetCollegesUniversityCollegeRoute: CuetCollegesUniversityCollegeRoute,
  CuetCollegesBestForCourseRoute: CuetCollegesBestForCourseRoute,
  CuetCutoffCollegesForBandRoute: CuetCutoffCollegesForBandRoute,
  IpmatProgrammeInstituteFeesRoute: IpmatProgrammeInstituteFeesRoute,
  CuetResultsCollegePredictorIndexRoute: CuetResultsCollegePredictorIndexRoute,
  CuetCutoffUniversityCollegeCourseRoute:
    CuetCutoffUniversityCollegeCourseRoute,
  CuetResultsCollegePredictorUniversityCourseRoute:
    CuetResultsCollegePredictorUniversityCourseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
